[package]
name = "needleman_wunsch"
version = "0.1.0"
authors = ["Laurent Bloch <lb@laurentbloch.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
simple-matrix = "0.1"
# ordered-float = "2.0"
